print("repr tests...")
print("repr(None) -> " + repr(None))
print("repr(True) -> " + repr(True))
print("repr(not True) -> " + repr(not True))
print("repr(5) -> " + repr(5))
print("repr(-5) -> " + repr(-5))
print("repr(5 + 11) -> " + repr(5 + 11))
print("repr(6.0) -> " + repr(6.0))
print("repr(6.0 + 3) -> " + repr(6.0 + 3))
print("repr(-6.0 + 3) -> " + repr(-6.0 + 3))
print("repr(b'omg') -> " + repr(b'omg'))
print("repr(b'omg' + b'hax') -> " + repr(b'omg' + b'hax'))
print("repr('omg') -> " + repr('omg'))
print("repr('omg' + 'hax') -> " + repr('omg' + 'hax'))
